% Run from directory containing this analysis script
dDir=fullfile(pwd,'data');
cd(dDir)
nameList={ '1. N2'...
    '2. rab-3::HyPep',...
    '3. myo-3::HyCal',...
    '4. rab-3::HyPep; myo-3::HyCal',...
    '5. unc-47::HyCal',...
    '6. rab-3::HyPep; unc-47::HyCal',...
    '7. rab-3::HyCal',...
    '8. rab-3::HyPep; rab-3::HyCal'};
txtY=410;
pFR=30; % 30fps is real-time, this is 10-fold slower

[headAVs,groups] = headAngVelWrapper(dDir,...
    'sampLabels',nameList,'pFR',pFR,...
    'txtY',txtY,'saveDir',fullfile(dDir,'vidOut'),...
    'vQC',1);
